config/routes.rb
Rails.application.routes.draw do
  post 'authenticate' => 'users#authenticate'
  get   'login'   => 'sessions#new'
  post  'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get   'search'    => 'search_pages#search'
  post 'facts/:id'  => 'facts#delete'
  get 'gcm' =>  'users#send_message'

  root  'search_pages#search'

  resources :facts
  resources :variables
  resources :users do
    resources :groups
  end

  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :account_activations, only: [:new, :edit]

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :get_user, only: [:edit, :update]
  before_action :check_expiration, only: [:edit, :update]

  def new
  end

  def edit
  end

  def create
    puts "Hit Create!!"
    email = params[:password_reset][:email]
  	user = User.find_by(email: email.downcase)
  	if user
      user.create_password_reset_digest
      user.send_password_reset_email
  		flash[:success] = "Password reset instruction send to #{email}"
  		redirect_to root_path
  	else
  		flash.now[:danger] = "#{email} is not registered email"
  		render 'new'
  	end
  end

  def update
    if params[:user][:password].empty?
      @user.errors.add(:password, "can't be empty")
      render 'edit'
    elsif @user.update_attributes(user_params)
      log_in_user @user
      flash[:success] = "Password has been reset."
      redirect_to root_path
    else
      render 'edit'
    end
  end

  private
    def user_params
      params.require(:user).permit(:password, :password_confirmation)
    end

    def get_user
      @user = User.find_by(email: params[:email])
    end

    # Checks expiration of reset token.
    def check_expiration
      if @user.password_reset_expired?
        flash[:danger] = "Password reset has expired."
        redirect_to new_password_reset_url
      end
    end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<h1>Password Reset</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= render 'shared/error_messages', object: @user %>
		<%= form_for(@user, url: password_reset_url(controller: "PasswordResetsController", action: "update"), method: "patch", html: {novalidate: 'novalidate'}) do |f| %>
			<%= hidden_field_tag :email, @user.email %>
			<%= f.label :password %>
			<%= f.password_field :password, class: "form-control" %>
			<%= f.label :password_confirmation %>
			<%= f.password_field :password_confirmation, class: "form-control" %>
			<%= f.submit "Update Password", class: "btn btn-primary form-control" %>
		<% end %>
	</div>
</div>

app/views/password_resets/new.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">

		<%= form_for(:password_reset, url: password_resets_path) do |f| %>
		<%= f.label :email %>
		<%= f.email_field :email, value: params.fetch(:password_reset, {})[:email], class: "form-control" %>
		<%= f.submit "Send", class: "btn btn-primary form-control" %>
		<% end %>
	</div>
</div>