config/routes.rb
Rails.application.routes.draw do
  post 'authenticate' => 'users#authenticate'
  get   'login'   => 'sessions#new'
  post  'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get   'search'    => 'search_pages#search'
  post 'facts/:id'  => 'facts#delete'
  get 'gcm' =>  'users#send_message'

  root  'search_pages#search'

  resources :facts
  resources :variables
  resources :users do
    resources :groups
  end

  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :account_activations, only: [:new, :edit]

end

app/models/fact.rb
class Fact < ActiveRecord::Base
	default_scope { order('updated_at DESC') }
	belongs_to :user
	belongs_to :group
	has_one :relationship
	has_one :category, through: :relationship
	has_many   :attachments
end

app/controllers/facts_controller.rb
class FactsController < ApplicationController

  	def index
  		query = (params[:query] || params[:q] || '').downcase
      user_id = params.fetch(:user_id, nil)
      user_ids = [user_id]
      user_ids.push(nil) if [true, "true", "1"].include?(params.fetch(:include_anon, false))
      @facts = Fact.all.where({user_id: user_ids.uniq})
      @facts = @facts.map {|fact| fact if fact.content.downcase.include? query}.compact

      respond_to do |format|
        format.html
        format.json do
          users = @facts.map(&:user).uniq.compact
          groups = @facts.map(&:group).uniq.compact
          res = { facts: @facts, users: users, groups: groups }
          puts "Result #{res}"
          render json: res
        end
      end
  	end

  	def new
  		@fact = Fact.new
  	end

    def edit
      @fact = Fact.find(params[:id])

      respond_to do |format|
        format.html { render partial: 'shared/edit_fact', locals: {'fact' => @fact} }
        format.js
      end
    end

  	def create
  		@fact = Fact.new(fact_params)
      puts "PARAMS #{fact_params}"
      @fact.update_attribute(:user_id, current_user.id) if current_user
  		@fact.save

      respond_to do |format|
        format.html { render @fact }
        format.js
        format.json { render json: { fact: @fact }}
      end
  	end

    def update
      @fact = Fact.find(params[:id])
      @fact.update_attributes(fact_params)
      
      respond_to do |format|
        format.html {render fact}
        format.js
      end
    end

    def delete
      @fact = Fact.find(params[:id])
      @fact.update_attribute(:deleted, true)
      puts "PARAMS #{params} #{@fact.to_json}"
      respond_to do |format|
        format.json { render json: { fact: @fact } }
      end
    end

    def destroy
      @fact = Fact.find(params[:id])
      @fact.destroy

      respond_to do |format|
        format.html { redirect_to facts_url }
        format.js   { render :layout => false }
      end
    end

    def status
      query = (params[:query] || params[:q] || '').downcase
      user_ids = [params.fetch(:user_id, nil)]
      user_ids.push(nil) if [true, "true", "1"].include?(params.fetch(:include_anon, false))
      @facts = Fact.all.where({user_id: user_ids.uniq})
    end

  	private
  		def fact_params
  			params.require(:fact).permit(:content, :user_id)
  		end
end

app/helpers/facts_helper.rb
module FactsHelper
end

app/views/facts/_fact.html.erb
<% @query = local_assigns.fetch(:query, '') %>

<div class="panel panel-default search-result" id=<%= "fact-#{fact.id}"%> data-id=<%= "#{fact.id}" %> >
	<div class="panel-body">
		<% if not @query.blank? %>
			<p><%= raw fact.content.sub(@query, "<mark>#{@query}</mark>") %></p>
		<% else %>
			<p><%= fact.content %></p>
		<% end %>
		<div class="btn-group search-result-control pull-right">
			<%= link_to 'Edit', edit_fact_path(fact), method: :get, remote: true, class: 'btn btn-default' %> 
			<%= link_to 'Delete', fact, method: :delete, remote: true, class: 'btn btn-default' %> 
		</div>
	</div>
</div>

app/views/facts/create.js.erb
$searchResults = $("#search-results .search-result");

if ($searchResults.length == 0){
	$("#search-results").html("<%= escape_javascript(render(@fact)) %>");
}else{
	$searchResults.first().before("<%= escape_javascript(render(@fact)) %>");
}

$searchResults.first().hide().slideDown('fast');

app/views/facts/destroy.js.erb
var factId = <%= params[:id] %>;
<%= puts "Fact ID: #{params}" %>
$('#fact-' + factId).slideUp('fast');

app/views/facts/edit.js.erb
<% @fact = Fact.find(params[:id]) %>
var txt = '<%= escape_javascript(@fact.content) %>';

var f = $('<%= escape_javascript(render(partial: "shared/edit_fact", locals:{"fact" => @fact})) %>');
var body = f.find('form').addClass('panel-body');
body.find('.panel-footer').removeClass('panel-footer').addClass('form-group');
body.find(':submit').addClass('pull-right "form-control"');
console.log(body.get());

// var $textArea = $('<textarea class="form-control"/>');
// $textArea.text(txt);
// console.log($('#fact-' + <%= @fact.id %> + ' p'));
$('#fact-' + <%= @fact.id %> + ' .panel-body').first().replaceWith(body);

app/views/facts/index.html.erb
<ul>
	<% @facts.each do |fact| %>
		<li>
			<div class="card">
				<div class="card-block">
					<p class="card-text"><%= fact.content %></p>
				</div>
			</div>
		</li>
	<% end %>
</ul>

app/views/facts/new.html.erb
<h1>Facts#new</h1>
<p><%= @fact.content %></p>

app/views/facts/update.js.erb
$('#fact-' + <%= @fact.id %>).replaceWith($('<%= escape_javascript(render(@fact)) %>'));