config/routes.rb
Rails.application.routes.draw do
  post 'authenticate' => 'users#authenticate'
  get   'login'   => 'sessions#new'
  post  'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get   'search'    => 'search_pages#search'
  post 'facts/:id'  => 'facts#delete'
  get 'gcm' =>  'users#send_message'

  root  'search_pages#search'

  resources :facts
  resources :variables
  resources :users do
    resources :groups
  end

  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :account_activations, only: [:new, :edit]

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Quick Facts</a>
    by <a href="http://www.michaelhartl.com/">Aetos Labs</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   "#" %></li>
      <li><%= link_to "Contact", "#" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "quick facts", root_path, id: "logo", class: "_navbar-brand"%>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if current_user %>
        	<li class="dropdown">
        		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"/></a>
        		<ul class="dropdown-menu">
                    <% if current_user.admin %>
                        <li><%= link_to "All users", users_path %></li>
                    <% end %>
        			<li><%= link_to "Preferences", root_path %></li>
        			<li role="separator" class="divider"/>
        			<li><%= link_to "Log out", logout_path, method: :delete %></li> 
        		</ul>
        	</li>
        <% else %>
        	<li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= get_page_title(yield :title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Lato&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</head>
	<body class="<%= controller_name %> <%= action_name %>">
		<%= render "layouts/header" %>
		<div class="container">
			<% flash.each do |msg_type, msg| %>
				<div class="alert alert-<%= msg_type %> alert-dismissible" role="alert">
					<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
						<span><%= raw msg %></span>
				</div>
			<% end %>
			<%= yield %>
			<%= render "layouts/footer" %>

			<div class="app-store">
                <ul>
                    <li><a href="https://play.google.com/store/apps/details?id=com.aetoslabs.quickfacts" target="_blank" class="google-play"></a></li>
                </ul>
            </div>

			<%= debug(params) if Rails.env.development? %>

		</div>

        <script>
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

            ga('create', 'UA-72864928-1', 'auto');
            ga('send', 'pageview');

        </script>
	</body>
</html>